import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Canvas to dynamically compute and render 'Page X of Y' page numbers.
    Also handles standard headers and footers on each page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        self.saveState()
        
        # Primary colors
        primary_color = colors.HexColor("#1e3d59") # Dark slate blue
        accent_color = colors.HexColor("#17b978")  # Health green
        text_color = colors.HexColor("#555555")
        
        # Draw top thin banner
        self.setFillColor(primary_color)
        self.rect(0, 770, 612, 22, fill=True, stroke=False)
        self.setFillColor(colors.white)
        self.setFont("Helvetica-Bold", 8)
        self.drawString(36, 777, "CLINICAL RADIOLOGY AUTOMATION SYSTEM")
        
        # Draw bottom page numbers and disclaimer
        self.setFillColor(text_color)
        self.setFont("Helvetica", 7)
        disclaimer = "CONFIDENTIAL - CLINICAL USE ONLY. Generated by AI Assistant. Clinical correlation is mandatory."
        self.drawString(36, 30, disclaimer)
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 30, page_str)
        
        # Draw bottom accent line
        self.setStrokeColor(accent_color)
        self.setLineWidth(1)
        self.line(36, 45, 576, 45)
        
        self.restoreState()

def generate_radiology_pdf(output_path, findings, impression, recommendations, image_name):
    """
    Generates a clean, professional, print-ready PDF radiology report.
    """
    # Ensure the directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Page setup: letter size with 0.5 inch (36 pt) margins
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    # Primary Palette
    c_primary = colors.HexColor("#1e3d59")   # Deep navy
    c_accent = colors.HexColor("#17b978")    # Emerald medical green
    c_dark = colors.HexColor("#222222")      # Off-black body
    c_light = colors.HexColor("#f8f9fa")     # Soft grey background
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=c_primary
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#777777")
    )
    
    section_title_style = ParagraphStyle(
        'SectionTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=c_primary,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=15,
        textColor=c_dark
    )
    
    impression_body_style = ParagraphStyle(
        'ImpressionBody',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=15,
        textColor=colors.HexColor("#b83b5e") # Crimson red accent for clinical impression
    )
    
    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=c_primary
    )
    
    meta_val_style = ParagraphStyle(
        'MetaVal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=c_dark
    )

    story = []
    
    # 1. Document Title Section
    story.append(Spacer(1, 15))
    story.append(Paragraph("CHEST X-RAY RADIOLOGY REPORT", title_style))
    story.append(Paragraph("Automated Clinical Analysis & Findings Generator", subtitle_style))
    story.append(Spacer(1, 15))
    
    # 2. Metadata Table
    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_id = f"CXR-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    
    meta_data = [
        [
            Paragraph("Report ID:", meta_label_style), Paragraph(report_id, meta_val_style),
            Paragraph("Date / Time:", meta_label_style), Paragraph(timestamp_str, meta_val_style)
        ],
        [
            Paragraph("Source Image:", meta_label_style), Paragraph(image_name, meta_val_style),
            Paragraph("Modality:", meta_label_style), Paragraph("Chest X-Ray (CXR)", meta_val_style)
        ],
        [
            Paragraph("Procedure:", meta_label_style), Paragraph("Chest PA/Lateral View", meta_val_style),
            Paragraph("Status:", meta_label_style), Paragraph("Generated - Pending Signoff", meta_val_style)
        ]
    ]
    
    # 540 pt is the printable width (612 - 72)
    meta_table = Table(meta_data, colWidths=[100, 170, 100, 170])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), c_light),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ('BOX', (0, 0), (-1, -1), 1, c_primary),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 25))
    
    # Helper to draw horizontal separators
    def create_separator():
        sep_table = Table([['']], colWidths=[540])
        sep_table.setStyle(TableStyle([
            ('LINEBELOW', (0, 0), (-1, -1), 1.5, c_primary),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        return sep_table
    
    # 3. Findings Section
    story.append(Paragraph("CLINICAL FINDINGS", section_title_style))
    story.append(create_separator())
    story.append(Spacer(1, 8))
    
    findings_para = findings.replace("\n", "<br/>")
    story.append(Paragraph(findings_para, body_style))
    story.append(Spacer(1, 20))
    
    # 4. Impression Section (in a highlighted alert block)
    story.append(Paragraph("IMPRESSION", section_title_style))
    story.append(create_separator())
    story.append(Spacer(1, 8))
    
    impression_para = impression.replace("\n", "<br/>")
    impression_table_data = [[Paragraph(impression_para, impression_body_style)]]
    impression_table = Table(impression_table_data, colWidths=[540])
    impression_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#fff5f5")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#f3c6c6")),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(impression_table)
    story.append(Spacer(1, 20))
    
    # 5. Recommendations Section
    story.append(Paragraph("RECOMMENDATIONS", section_title_style))
    story.append(create_separator())
    story.append(Spacer(1, 8))
    
    recs_para = recommendations.replace("\n", "<br/>")
    story.append(Paragraph(recs_para, body_style))
    story.append(Spacer(1, 35))
    
    # 6. Signature Block
    sig_data = [
        [
            Paragraph("<b>Electronically signed by:</b>", meta_label_style),
            Paragraph("<b>Verified by:</b>", meta_label_style)
        ],
        [
            Paragraph("AI Radiology Report Generator Agent<br/>AI-CXR Engine v1.0", meta_val_style),
            Paragraph("Clinical Specialist Reviewer (Signoff Pending)<br/>M.D., Radiologist", meta_val_style)
        ]
    ]
    sig_table = Table(sig_data, colWidths=[270, 270])
    sig_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(KeepTogether(sig_table))

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)
